if (CCL_LIBCPP OR APPLE)
    add_compile_options(-stdlib=libc++)
    add_link_options(-stdlib=libc++ -lc++abi)
else ()
    add_compile_options(-stdlib=libstdc++)
    add_link_options(-stdlib=libstdc++)
endif ()

if (CCL_ADDRESS_SANITIZER)
    add_compile_options(-fsanitize=nullability)
    add_link_options(-fsanitize=nullability)
endif ()